# Generated by Django 5.1.2 on 2024-10-14 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='favorite', to='customers.customer')),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='favorites.favorite')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('image', models.URLField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('review_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('link', models.CharField(max_length=255)),
                ('favorites', models.ManyToManyField(blank=True, through='favorites.FavoriteProduct', to='favorites.favorite')),
            ],
        ),
        migrations.AddField(
            model_name='favoriteproduct',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='favorites.product'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='products',
            field=models.ManyToManyField(blank=True, through='favorites.FavoriteProduct', to='favorites.product'),
        ),
        migrations.AlterUniqueTogether(
            name='favoriteproduct',
            unique_together={('favorite', 'product')},
        ),
    ]
