# Generated by Django 5.1.2 on 2024-10-13 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0002_alter_favorite_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='link',
            field=models.CharField(max_length=255),
        ),
    ]
