line-length = 120
indent-width = 4
extend-exclude = ["migrations"]

[lint]
preview = true
select = ["I", "F", "E", "W", "PL", "PT"]
ignore = ["E402", "F811", "PLC0415"]

[format]
preview = true
quote-style = "double"
indent-style = "space"
line-ending = "auto"
docstring-code-format = false
